# Generated by Django 5.1.6 on 2025-03-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirelisting',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
