# Generated by Django 5.1.6 on 2025-03-01 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_tirelisting_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='listingimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.tirelisting'),
        ),
    ]
