# Generated by Django 5.1.6 on 2025-03-27 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_listingimage_options_listingimage_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tirelisting',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='tirelisting',
            name='marketplace_seller__a7b521_idx',
        ),
        migrations.AddField(
            model_name='tirelisting',
            name='vehicle_type',
            field=models.CharField(choices=[('passenger', 'Passenger Car'), ('suv', 'SUV'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('van', 'Van'), ('others', 'Others')], default='passenger', max_length=20),
        ),
        migrations.AlterField(
            model_name='tirelisting',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tirelisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
