# Generated by Django 5.1.6 on 2025-05-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tire_images/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='tire_images/thumbnails/'),
        ),
    ]
