# Generated by Django 5.1.6 on 2025-06-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_remove_listingimage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirelisting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
