// List of tire brands for the multi-select dropdown
export const tireBrands = [
  { label: "Apollo", value: "Apollo" },
  { label: "Atturo", value: "Atturo" },
  { label: "Avon", value: "Avon" },
  { label: "Barum", value: "Barum" },
  { label: "BFGoodrich", value: "BFGoodrich" },
  { label: "Bridgestone", value: "Bridgestone" },
  { label: "Carlisle", value: "Carlisle" },
  { label: "Continental", value: "Continental" },
  { label: "Cooper Tires", value: "Cooper Tires" },
  { label: "Dayton", value: "Dayton" },
  { label: "Dean", value: "Dean" },
  { label: "Debica", value: "Debica" },
  { label: "Dick Cepek", value: "Dick Cepek" },
  { label: "Double Coin", value: "Double Coin" },
  { label: "Dunlop", value: "Dunlop" },
  { label: "Falken", value: "Falken" },
  { label: "Firestone", value: "Firestone" },
  { label: "Fulda", value: "Fulda" },
  { label: "Fuzion", value: "Fuzion" },
  { label: "General", value: "General" },
  { label: "Gislaved", value: "Gislaved" },
  { label: "Giti", value: "Giti" },
  { label: "Goodyear", value: "Goodyear" },
  { label: "GT Radial", value: "GT Radial" },
  { label: "Hankook", value: "Hankook" },
  { label: "Kelly Tires", value: "Kelly Tires" },
  { label: "Kenda", value: "Kenda" },
  { label: "Kleber", value: "Kleber" },
  { label: "Kumho", value: "Kumho" },
  { label: "Laufenn", value: "Laufenn" },
  { label: "Linglong", value: "Linglong" },
  { label: "Mastercraft", value: "Mastercraft" },
  { label: "Maxxis", value: "Maxxis" },
  { label: "Michelin", value: "Michelin" },
  { label: "Mickey Thompson", value: "Mickey Thompson" },
  { label: "Nexen", value: "Nexen" },
  { label: "Nitto", value: "Nitto" },
  { label: "Nokian", value: "Nokian" },
  { label: "Ohtsu", value: "Ohtsu" },
  { label: "Pirelli", value: "Pirelli" },
  { label: "Roadmaster", value: "Roadmaster" },
  { label: "Roadstone", value: "Roadstone" },
  { label: "Sailun", value: "Sailun" },
  { label: "Sava", value: "Sava" },
  { label: "Seiberling", value: "Seiberling" },
  { label: "Semperit", value: "Semperit" },
  { label: "Starfire", value: "Starfire" },
  { label: "Sumitomo", value: "Sumitomo" },
  { label: "Toyo", value: "Toyo" },
  { label: "Uniroyal", value: "Uniroyal" },
  { label: "Viking", value: "Viking" },
  { label: "Vredestein", value: "Vredestein" },
  { label: "Yokohama", value: "Yokohama" }
]; 