import { StyleSheet } from 'react-native';

export const authStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  headerContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    padding: 16,
    paddingTop: 24,
    zIndex: 1,
  },
  logo: {
    fontSize: 20,
    fontWeight: '600',
    color: '#000000',
  },
  headerButton: {
    backgroundColor: '#2D4B3A',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    minWidth: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
    fontFamily: 'Poppins-Medium',
  },
  formContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  formBox: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#EBEDEC',
    padding: 32,
    borderRadius: 12,
  },
  title: {
    fontSize: 28,
    fontWeight: '600',
    marginBottom: 32,
    color: '#000000',
    textAlign: 'center',
    fontFamily: 'Poppins-SemiBold',
  },
  inputContainer: {
    position: 'relative',
    width: '100%',
    marginBottom: 16,
    zIndex: 1,
  },
  errorContainer: {
    width: '100%',
    marginBottom: 16,
    backgroundColor: '#FEE2E2',
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FCA5A5',
  },
  input: {
    width: '100%',
    fontFamily: 'Poppins-Regular',
    height: 40,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#A3B18A',
    borderRadius: 8,
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#3A5A40',
  },
  eyeButton: {
    position: 'absolute',
    right: 16,
    top: 8,  
  },
  forgotButton: {
    alignSelf: 'flex-end',
    marginBottom: 24,
  },
  forgotButtonText: {
    color: '#2D4B3A',
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
  },
  button: {
    backgroundColor: '#2D4B3A',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
    fontFamily: 'Poppins-Medium',
  },
  errorText: {
    color: '#FF0000',
    fontSize: 12,
    marginTop: 5,
    fontFamily: 'Poppins-Regular',
  },
  subtitle: {
    fontSize: 14,
    color: '#344E41',
    textAlign: 'center',
    marginBottom: 20,
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 20,
  },
  otpInput: {
    borderWidth: 1,
    borderColor: '#344E41',
    borderRadius: 8,
    width: 45,
    height: 45,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: 'bold',
    color: '#344E41',
    backgroundColor: '#FFFFFF',
  },
  successText: {
    color: '#2D4B3A',
    fontSize: 14,
    textAlign: 'center',
    backgroundColor: '#E9EDC9',
    padding: 12,
    borderRadius: 8,
    marginBottom: 24,
  },
  resendContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 15,
  },
  resendText: {
    color: '#344E41',
  },
  resendButton: {
    color: '#2D4B3A',
    fontWeight: 'bold',
  },
  resendTimer: {
    color: '#344E41',
    fontWeight: 'bold',
  },
  disabledText: {
    color: '#888888',
  },
  accountTypeContainer: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 24,
  },
  accountTypeButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#A3B18A',
    alignItems: 'center',
  },
  accountTypeButtonActive: {
    backgroundColor: '#2D4B3A',
    borderColor: '#2D4B3A',
  },
  accountTypeText: {
    color: '#2D4B3A',
    fontSize: 16,
    fontWeight: '500',
  },
  accountTypeTextActive: {
    color: '#FFFFFF',
  },
  gridContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: '50%',  // Covers the right half
    height: '50%', // Covers the top half
    display: 'flex',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gridTemplateRows: 'repeat(3, 1fr)',
    gap: 8,
    padding: 16,
    backgroundColor: '#f0f0f0',  // Light background for visibility
  },
  gridItem: {
    backgroundColor: '#2D4B3A',
    padding: 16,
    justifyContent: 'center',
    alignItems: 'center',
    display: 'flex',
    borderRadius: 8,
  },
  gridText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  gridTextActive: {
    color: '#2D4B3A',
  },
  gridTextInactive: {
    color: '#666666',
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  demoButton: {
    backgroundColor: '#4a6741',
    marginTop: 10,
  },
  radioContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  radioButton: {
    borderWidth: 1,
    borderColor: '#344E41',
    borderRadius: 5,
    padding: 10,
    width: '48%',
    alignItems: 'center',
  },
  radioButtonActive: {
    backgroundColor: '#344E41',
  },
  radioText: {
    color: '#344E41',
    fontWeight: 'bold',
  },
  radioTextActive: {
    color: '#FFFFFF',
  },
}); 