import { StyleSheet } from "react-native";

// Color scheme to match the Figma design exactly
const primaryColor = "#5B7560"; // Green from Figma
const secondaryColor = "#588157"; // Lighter green
const lightGrayColor = "#F5F5F5"; // Background color
const darkGrayColor = "#666666"; // Medium gray for text
const borderColor = "#E0E0E0"; // Border color
const textColor = "#333333"; // Text color
const backgroundColor = "#FFFFFF"; // White background
const starColor = "#FACC15"; // Yellow star color

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: lightGrayColor,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    backgroundColor: backgroundColor,
    borderBottomWidth: 1,
    borderBottomColor: borderColor,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  leftSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
  },
  logoText: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: textColor,
    letterSpacing: 0,
  },
  searchSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  searchContainer: {
    flex: 1,
    position: "relative",
  },
  searchInput: {
    height: 36,
    borderWidth: 1,
    borderColor: borderColor,
    borderRadius: 4,
    paddingLeft: 12,
    paddingRight: 40,
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    backgroundColor: backgroundColor,
    letterSpacing: 0,
  },
  searchButton: {
    position: "absolute",
    right: 0,
    top: 0,
    height: 36,
    width: 36,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: primaryColor,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
  },
  searchButtonIcon: {
    width: 20,
    height: 20,
    tintColor: backgroundColor,
  },
  searchSuggestions: {
    position: "absolute",
    top: 36,
    left: 0,
    right: 0,
    backgroundColor: backgroundColor,
    borderWidth: 1,
    borderColor: borderColor,
    borderRadius: 4,
    marginTop: 4,
    zIndex: 1000,
  },
  searchSuggestionItem: {
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: borderColor,
  },
  searchSuggestionText: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: textColor,
    letterSpacing: 0,
  },
  rightSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  upgradeButton: {
    backgroundColor: primaryColor,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 4,
  },
  upgradeButtonText: {
    color: backgroundColor,
    fontSize: 14,
    fontFamily: "Poppins-Medium",
    fontWeight: "500",
    letterSpacing: 0,
  },
  sellButton: {
    backgroundColor: backgroundColor,
    paddingVertical: 7,
    paddingHorizontal: 16,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: primaryColor,
  },
  sellButtonText: {
    color: primaryColor,
    fontSize: 14,
    fontFamily: "Poppins-Medium",
    fontWeight: "500",
    letterSpacing: 0,
  },
  cartButton: {
    position: "relative",
  },
  cartIcon: {
    width: 24,
    height: 24,
  },
  cartBadge: {
    position: "absolute",
    top: -6,
    right: -6,
    backgroundColor: primaryColor,
    borderRadius: 10,
    width: 16,
    height: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  cartBadgeText: {
    color: backgroundColor,
    fontSize: 10,
    fontFamily: "Poppins-Bold",
    fontWeight: "bold",
    letterSpacing: 0,
  },
  profileButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F5F5F5",
    justifyContent: "center",
    alignItems: "center",
  },
  profileIcon: {
    width: 24,
    height: 24,
  },
  mainContent: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#F5F5F5",
    padding: 20,
  },
  filterSidebar: {
    width: 240,
    backgroundColor: backgroundColor,
    borderRadius: 4,
    padding: 16,
    marginRight: 20,
  },
  productGrid: {
    flex: 1,
  },
  productsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 24,
    padding: 16,
  },
  sortByContainer: {
    alignSelf: "flex-end",
    marginBottom: 20,
    zIndex: 1000,
  },
  contentWrapper: {
    flexDirection: 'row',
    backgroundColor: lightGrayColor,
    paddingLeft: 20,
  },
  filterSection: {
    width: '20%',
    paddingVertical: 15,
    paddingHorizontal: 15,
    backgroundColor: backgroundColor,
    borderRightWidth: 0,
    marginRight: 15,
  },
  filterCategory: {
    marginBottom: 20,
  },
  filterCategoryTitle: {
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 12,
    color: textColor,
    fontFamily: "Poppins-SemiBold",
    letterSpacing: 0,
  },
  filterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  checkbox: {
    width: 16,
    height: 16,
    borderWidth: 1,
    borderColor: '#CCCCCC',
    backgroundColor: backgroundColor,
    borderRadius: 4,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkedBox: {
    width: 10,
    height: 10,
    backgroundColor: primaryColor,
    borderRadius: 1,
  },
  filterItemText: {
    fontSize: 13,
    color: darkGrayColor,
    fontFamily: "Poppins-Regular",
    letterSpacing: 0,
  },
  priceRangeContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
  },
  priceInput: {
    borderWidth: 1,
    borderColor: "#CCCCCC", // Matches Figma border color
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    width: "45%",
    fontSize: 13,
    backgroundColor: backgroundColor,
    color: darkGrayColor,
    fontFamily: "Poppins-Regular", // Updated to Poppins
  },
  priceRangeDash: {
    paddingHorizontal: 5,
    color: darkGrayColor,
  },
  tireSizeInput: {
    borderWidth: 1,
    borderColor: "#CCCCCC", // Matches Figma border color
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginBottom: 10,
    width: "100%",
    fontSize: 13,
    backgroundColor: backgroundColor,
    color: darkGrayColor,
    fontFamily: "Poppins-Regular", // Updated to Poppins
  },
  treadDepthContainer: {
    marginTop: 12,
    width: '100%',
    position: 'relative',
    zIndex: 1,
  },
  treadDepthTrack: {
    height: 4,
    backgroundColor: "#E5E7EB",
    borderRadius: 2,
    width: "100%",
    position: "relative",
  },
  treadDepthProgress: {
    height: 4,
    backgroundColor: primaryColor,
    borderRadius: 2,
    position: "absolute",
    left: 0,
  },
  treadDepthThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: primaryColor,
    borderWidth: 2,
    borderColor: backgroundColor,
    position: "absolute",
    top: -8,
    marginLeft: -10,
    cursor: 'pointer',
    zIndex: 2,
  },
  treadDepthLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 5,
  },
  treadDepthLabel: {
    fontSize: 12,
    color: darkGrayColor,
    fontFamily: "Poppins-Regular", // Updated to Poppins
  },
  treadDepthValue: {
    fontSize: 12,
    color: darkGrayColor,
    textAlign: 'center',
    marginTop: 5,
    fontFamily: "Poppins-Regular", // Updated to Poppins
  },
  productImageContainer: {
    flex: 1,
    padding: 15,
    backgroundColor: backgroundColor,
  },
  sortByButton: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#CCCCCC",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: backgroundColor,
    zIndex: 1000,
  },
  sortByText: {
    marginRight: 5,
    fontSize: 13,
    color: darkGrayColor,
    fontFamily: "Poppins-Regular", // Updated to Poppins
  },
  sortDropdownMenu: {
    position: "absolute",
    top: "100%",
    right: 0,
    backgroundColor: backgroundColor,
    borderWidth: 1,
    borderColor: "#CCCCCC",
    borderRadius: 4,
    marginTop: 4,
    zIndex: 1001,
    elevation: 5,
    minWidth: 180,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  productCard: {
    width: "31%",
    backgroundColor: backgroundColor,
    borderRadius: 8,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: borderColor,
    marginBottom: 24,
  },
  productCardHovered: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  productImage: {
    width: "100%",
    height: 180,
    backgroundColor: lightGrayColor,
    justifyContent: "center",
    alignItems: "center",
  },
  productInfo: {
    padding: 12,
  },
  productTitle: {
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 8,
    color: textColor,
    textAlign: "center",
    fontFamily: "Poppins-SemiBold",
    letterSpacing: 0,
  },
  productPrice: {
    fontSize: 14,
    fontWeight: "600",
    color: textColor,
    marginBottom: 5,
    backgroundColor: "#E0E0E0",
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderRadius: 4,
    alignSelf: "flex-start",
    fontFamily: "Poppins-SemiBold",
    letterSpacing: 0,
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  ratingText: {
    fontSize: 14,
    fontWeight: "500",
    color: textColor,
    marginRight: 5,
    fontFamily: "Poppins-Medium",
    letterSpacing: 0,
  },
  reviewCount: {
    fontSize: 12,
    color: darkGrayColor,
    marginLeft: 5,
    fontFamily: "Poppins-Regular",
    letterSpacing: 0,
  },
  starContainer: {
    flexDirection: "row",
  },
  star: {
    marginRight: 2,
    color: starColor,
  },
  productSpec: {
    fontSize: 13,
    color: darkGrayColor,
    marginBottom: 4,
    fontFamily: "Poppins-Regular",
    letterSpacing: 0,
  },
  addToCartButton: {
    backgroundColor: primaryColor,
    paddingVertical: 10,
    borderRadius: 4,
    alignItems: 'center',
    marginTop: 8,
  },
  addToCartButtonText: {
    color: backgroundColor,
    fontWeight: "bold",
    fontSize: 14,
    fontFamily: "Poppins-Bold",
    letterSpacing: 0,
  },
  speedRatingDropdown: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#CCCCCC", // Matches Figma border color
    borderRadius: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: backgroundColor,
    justifyContent: "space-between",
    width: "100%",
  },
  dropdownIcon: {
    fontSize: 12,
    color: darkGrayColor,
  },
  ratingStars: {
    flexDirection: "row",
    marginVertical: 5,
  },
  ratingStarFull: {
    color: starColor,
    fontSize: 16,
    marginRight: 2,
  },
  ratingStarEmpty: {
    color: "#D9D9D9",
    fontSize: 16,
    marginRight: 2,
  },
  vehicleTypeContainer: {
    marginTop: 5,
  },
  vehicleTypeText: {
    fontSize: 13,
    color: darkGrayColor,
    fontFamily: "Poppins-Regular", // Updated to Poppins
  },
  tireTypeContainer: {
    marginTop: 5,
  },
  tireTypeText: {
    fontSize: 13,
    color: darkGrayColor,
    fontFamily: "Poppins-Regular", // Updated to Poppins
  },
  ratingsContainer: {
    marginTop: 5,
  },
  ratingsStarRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Matches Figma overlay color
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '80%',
    backgroundColor: backgroundColor,
    borderRadius: 8,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 10,
  },
  closeButton: {
    padding: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
    color: textColor,
  },
  modalText: {
    fontSize: 14,
    marginBottom: 20,
    textAlign: 'center',
    color: darkGrayColor,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  modalButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 4,
    minWidth: 100,
    alignItems: 'center',
  },
  loginButton: {
    backgroundColor: primaryColor,
  },
  signupButton: {
    backgroundColor: secondaryColor,
  },
  modalButtonText: {
    color: backgroundColor,
    fontWeight: 'bold',
  },
  text: {
    fontFamily: "Poppins-Regular",
    letterSpacing: 0,
  },
});